name: Build CodeIgniter Zip

on:
  push:
    branches:
      - master # jalan tiap kamu push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies (optional)
        run: composer install --no-dev --optimize-autoloader || true

      - name: Prepare production build
        run: |
          mkdir build
          rsync -av --progress ./ build/ \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'tests' \
            --exclude 'node_modules' \
            --exclude 'composer.lock' \
            --exclude 'README.md'

      - name: Create ZIP file
        run: |
          cd build
          zip -r ../ci_build.zip .

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeigniter-build
          path: ci_build.zip
